# Generated by Django 3.2.23 on 2024-01-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='user_reply',
        ),
    ]
