# Generated by Django 3.2.23 on 2024-01-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_remove_inquiry_user_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry_images/'),
        ),
    ]
