# Generated by Django 3.2.23 on 2024-01-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_adminreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminReply',
        ),
    ]
